// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

require('dotenv').config();

const { google } = require('googleapis');
const path = require('path');

/**
 * Service responsible for authenticating and communicating with the Google Play Integrity API.
 *
 * Configured via .env variables:
 * - PACKAGE_NAME: The Android Application ID linked in the Play Console.
 * - GOOGLE_CREDENTIALS_PATH: The relative path to the Service Account JSON key.
 */
class IntegrityService {
    constructor() {
        if (!process.env.GOOGLE_CREDENTIALS_PATH) {
            throw new Error('🚨 CRITICAL: GOOGLE_CREDENTIALS_PATH is missing from your .env file.');
        }
        const keyFilePath = path.resolve(process.cwd(), process.env.GOOGLE_CREDENTIALS_PATH);
        const auth = new google.auth.GoogleAuth({
            keyFile: keyFilePath,
            scopes: ['https://www.googleapis.com/auth/playintegrity'],
        });
        this.playIntegrity = google.playintegrity({
            version: 'v1',
            auth: auth
        });
    }

    /**
     * Decodes the Play Integrity Token via Google's servers.
     * @param {string} integrityToken - The token generated by the Android client
     * @returns {Promise<Object>} Decoded token payload containing security verdicts
     */
    async decodeToken(integrityToken) {
        try {
            const packageName = process.env.PACKAGE_NAME;
            if (!packageName) {
                throw new Error('PACKAGE_NAME is missing from your .env file.');
            }

            console.log('\n[PlayIntegrityAPI] --- Initiating Decode Request ---');
            console.log('[PlayIntegrityAPI] Package Name: ' + packageName);

            // The first 15 characters are identical for tokens from the same warm-up request.
            // Logging the first and last 10 characters makes it easier to distinguish between them.
            const tokenPreview = integrityToken.length > 20
                ? integrityToken.substring(0, 10) + '...' + integrityToken.slice(-10)
                : integrityToken;
            console.log('[PlayIntegrityAPI] Token: ' + tokenPreview);

            const response = await this.playIntegrity.v1.decodeIntegrityToken({
                packageName: packageName,
                requestBody: {
                    integrityToken: integrityToken
                }
            });

            console.log('[PlayIntegrityAPI] --- Google API Response: SUCCESS ---');
            console.log('[PlayIntegrityAPI] Payload:', JSON.stringify(response.data.tokenPayloadExternal, null, 2));
            return response.data.tokenPayloadExternal;

        } catch (error) {
            console.error('\n[PlayIntegrityAPI] --- Error Decoding Token ---');

            if (error.code === 'ENOENT') {
                console.error('🚨 CRITICAL: Could not find credentials file at ' + error.path);
                console.error('Please check the GOOGLE_CREDENTIALS_PATH in your .env file!');
            }
            else if (error.response && error.response.data) {
                console.error(JSON.stringify(error.response.data, null, 2));
            }
            else {
                console.error('🚨 ERROR: ' + error.message);
            }

            console.error('-----------------------------------\n');
            throw new Error('FAILED_TO_DECODE_TOKEN');
        }
    }
}

module.exports = new IntegrityService();
