// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

const { INTEGRITY_VERDICTS } = require('../../config/constants');

/**
 * Defines the security policies for the Bank micro-app.
 *
 * NOTE FOR PRODUCTION: In a real-world application, a single Policy class
 * would typically contain multiple evaluation methods tailored to different
 * feature risks. For example, you might have `evaluateLoginPolicy()`
 * (requiring device integrity) alongside `evaluateLoanRequestPolicy()`
 * (requiring strong integrity).
 */
class BankPolicy {

    /**
     * Evaluates the Play Integrity verdicts specifically for a hypothetical
     * money transfer.
     *
     * @param {Object} tokenPayload
     * @returns {boolean} True if all checks pass, false otherwise.
     */
    evaluateTransferPolicy(tokenPayload) {
        // Abort if the token was generated by another app; no need to check verdicts.
        if(tokenPayload.requestDetails?.requestPackageName !== process.env.PACKAGE_NAME){
            return false;
        }

        const deviceRecognitionVerdict = tokenPayload.deviceIntegrity?.deviceRecognitionVerdict || [];
        const appRecognitionVerdict = tokenPayload.appIntegrity?.appRecognitionVerdict;
        const appLicensingVerdict = tokenPayload.accountDetails?.appLicensingVerdict;

        // Check Device Integrity: Must meet at least DEVICE_INTEGRITY
        const hasValidDevice =
            deviceRecognitionVerdict.includes(INTEGRITY_VERDICTS.DEVICE.MEETS_DEVICE_INTEGRITY)

        if (!hasValidDevice) return false;

        // Check App Integrity: Must be a recognized version from Google Play
        if (appRecognitionVerdict !== INTEGRITY_VERDICTS.APP.PLAY_RECOGNIZED) return false;

        // Check Account Details: User must have a Play license to the app
        return appLicensingVerdict === INTEGRITY_VERDICTS.ACCOUNT.LICENSED;
    }
}

module.exports = new BankPolicy();